# Locate FLEXERA
# This module defines
# FLEXERA_LIBRARY
# FLEXERA_FOUND, if false, do not try to link to FLEXERA
# FLEXERA_INCLUDE_DIR, where to find the headers
#
# $FLEXERA_DIR is an environment variable that would
# correspond to the ./configure --prefix=$FLEXERA_DIR
#

FIND_PATH(FLEXERA_INCLUDE_DIR lmclient.h
    
    ${FLEXERA_DIR}/include
    NO_DEFAULT_PATH
)

MACRO(FIND_FLEXERA_LIBRARY MYLIBRARY MYLIBRARYNAME)

	FIND_LIBRARY(     ${MYLIBRARY}
          NAMES       ${MYLIBRARYNAME}
          PATHS
          ${FLEXERA_DIR}/lib
      NO_DEFAULT_PATH
      )

ENDMACRO(FIND_FLEXERA_LIBRARY)


FIND_FILE(FLEXERA_TARGET_OBJ lm_new_md.obj
		  ${OSSROOT}/flexera/11.12/obj
		  )

FIND_FLEXERA_LIBRARY(FLEXERA_LMGR_LIBRARY 				lmgr_trl)
FIND_FLEXERA_LIBRARY(FLEXERA_SB_LIBRARY 				libsb)
FIND_FLEXERA_LIBRARY(FLEXERA_CRVS_LIBRARY 				libcrvs)
FIND_FLEXERA_LIBRARY(FLEXERA_ACT_LIBRARY 				libnoact)
FIND_FLEXERA_LIBRARY(FLEXERA_LMGRDONGLE_LIBRARY 		lmgr_dongle_stub)

SET(FLEXERA_LIBRARIES
	${FLEXERA_LMGR_LIBRARY}
	${FLEXERA_CRVS_LIBRARY}
	${FLEXERA_SB_LIBRARY}
	${FLEXERA_ACT_LIBRARY}
	${FLEXERA_LMGRDONGLE_LIBRARY}
	netapi32.lib
	comctl32.lib
	ws2_32.lib
	Wbemuuid.lib
	wintrust.lib
	crypt32.lib
	)

SET(FLEXERA_FOUND "NO")
IF(FLEXERA_LMGR_LIBRARY AND FLEXERA_INCLUDE_DIR )
    SET(FLEXERA_FOUND "YES")
ELSE(FLEXERA_LMGR_LIBRARY AND FLEXERA_INCLUDE_DIR )
    MESSAGE(STATUS "FLEXERA include at: " 			${FLEXERA_INCLUDE_DIR})
    MESSAGE(STATUS "FLEXERA obj: " 					${FLEXERA_TARGET_OBJ})
    MESSAGE(STATUS "FLEXERA lib should be found at: " $ENV{FLEXERA_DIR}/lib/${OS}/$ENV{COMPILER}/$ENV{OSSARCH}/$ENV{OSSBUILD})
	MESSAGE(STATUS "Cannot find FLEXERA!!!!!!!!!!!!!!!!")
ENDIF(FLEXERA_LMGR_LIBRARY AND FLEXERA_INCLUDE_DIR )

install(FILES 	${FLEXERA_DIR}/bin/libsimplifier.dll
				${FLEXERA_DIR}/bin/lmcrypt.exe
				${FLEXERA_DIR}/bin/lmnewgen.exe
		DESTINATION ${CMAKE_INSTALL_PREFIX}/bin )
