# This module defines the binary to access server app content meta data

FIND_PATH(SERVER_CONTENT_API_INCLUDE_DIR  AppContentApi.h  
		$ENV{SERVER_CONTENT_API_DIR}/include
		NO_DEFAULT_PATH    
)

find_library(SERVER_CONTENT_API_LIBRARY 
		NAMES ServerContentApi
		PATHS $ENV{SERVER_CONTENT_API_DIR}/lib/
		NO_DEFAULT_PATH    
)

find_library(SERVER_CONTENT_API_LIBRARY_D 
		NAMES ServerContentApid
		PATHS $ENV{SERVER_CONTENT_API_DIR}/lib/
		NO_DEFAULT_PATH    
)

SET(SERVER_CONTENT_API_FOUND "NO")
IF(SERVER_CONTENT_API_LIBRARY AND SERVER_CONTENT_API_INCLUDE_DIR )
    SET(SERVER_CONTENT_API_FOUND "YES")
ELSE(SERVER_CONTENT_API_LIBRARY ANDSERVER_CONTENT_API_INCLUDE_DIR)
    MESSAGE("SERVER_CONTENT_API Not Found")
ENDIF(SERVER_CONTENT_API_LIBRARY AND SERVER_CONTENT_API_INCLUDE_DIR)

install(DIRECTORY $ENV{SERVER_CONTENT_API_DIR}/bin/
		DESTINATION ${CMAKE_INSTALL_PREFIX}/bin )
