# INSTALL and SOURCE_GROUP commands for INDIGIS3D Modules

# Required Vars:
# ${LIB_NAME}
# ${LIB_PUBLIC_HEADERS}

#SET(INSTALL_INCDIR include)

STRING(REGEX REPLACE "\\\\" "/" INDIGIS3D_DIR_UNIV "$ENV{INDIGIS3D_DIR}")

SET(INSTALL_BINDIR bin/$ENV{OSSARCH})
SET(INSTALL_GDALDATA data/gdal)
SET(INSTALL_CONFIGDIR config)
SET(INSTALL_TESTSDIR tests)

# Reading dependency libraries
FILE(GLOB SQLITE_BINARIES "$ENV{SQLITE_BIN}/*.dll")
FILE(GLOB SPATIALITE_BIN "$ENV{SPATIALITE_BIN}/*.dll")
FILE(GLOB PROJ_BIN "$ENV{PROJ_BIN}/*.dll")
FILE(GLOB ICONV_BIN "$ENV{ICONV_BIN}/*.dll")
FILE(GLOB GEOS_BIN "$ENV{GEOS_BIN}/*.dll")
FILE(GLOB XERCESC_BIN "$ENV{XERCESC_BIN}/*.dll")
FILE(GLOB OSG_LIB "$ENV{OSG_LIB}/*.dll")
FILE(GLOB OSGCONV "$ENV{OSG_DIR}/bin/$ENV{OSSARCH}/osgconv.exe")
FILE(GLOB OSGVIEWER "$ENV{OSG_DIR}/bin/$ENV{OSSARCH}/osgviewer.exe")
FILE(GLOB OSG_PLUGINS "$ENV{OSG_DIR}/lib/$ENV{OSSARCH}/osgPlugins-2.9.10/*.dll")
FILE(GLOB GDAL_LIB "$ENV{GDAL_LIB}/*.dll")
#FILE(GLOB GDAL_DATA "$ENV{GDAL_DATA}/*")
FILE(GLOB GDAL_EXE "$ENV{GDAL_DIR}/bin/$ENV{OSSARCH}/*.exe")
FILE(GLOB OSGEARTH_LIB "$ENV{OSGEARTH_LIB}/*.dll")
FILE(GLOB OSGEARTH_BIN "$ENV{OSGEARTH_DIR}/bin/$ENV{OSSARCH}/*.exe")
FILE(GLOB CURL_DEBUG_LIBS "$ENV{CURL_DIR}/lib/$ENV{OSSARCH}/debug/*.dll")
FILE(GLOB CURL_DEBUG_EXE "$ENV{CURL_DIR}/bin/$ENV{OSSARCH}/debug/*.exe")
FILE(GLOB CURL_RELEASE_LIBS "$ENV{CURL_DIR}/lib/$ENV{OSSARCH}/release/*.dll")
FILE(GLOB CURL_RELEASE_EXE "$ENV{CURL_DIR}/bin/$ENV{OSSARCH}/release/*.exe")
FILE(GLOB EXPAT_BIN "$ENV{EXPAT_BIN}/*.dll")
FILE(GLOB PROJ_BIN "$ENV{PROJ_BIN}/*.dll")
FILE(GLOB TIFF_BIN "$ENV{TIFF_BIN}/*.dll")
FILE(GLOB BOOST_BIN "$ENV{BOOST_BIN}/*.dll")
FILE(GLOB JPEG_BIN "$ENV{JPEG_BIN}/*.dll")
FILE(GLOB ZLIB_BIN "$ENV{ZLIB_BIN}/*.dll")
FILE(GLOB PNG_BIN "$ENV{ZLIB_BIN}/*.dll")
FILE(GLOB FFMPEG_DLLS "$ENV{FFMPEG_BIN}/*.dll")
FILE(GLOB FFMPEG_EXE "$ENV{FFMPEG_BIN}/*.exe")
FILE(GLOB QWT_BIN "$ENV{QWT_BIN}/*.dll")
FILE(GLOB QT_BIN "$ENV{QT_BIN}/*.dll")

# Copy INDIGIS3D binaries and files
FILE(GLOB INDIGIS3D_LIBS "${INDIGIS3D_DIR_UNIV}/bin/win32/*.dll")
FILE(GLOB INDIGIS3D_EARTH "${INDIGIS3D_DIR_UNIV}/bin/win32/*.earth")
FILE(GLOB INDIGIS3D_PLUGINS "${INDIGIS3D_DIR_UNIV}/bin/win32/indiDBPlugins/*.dll")
FILE(GLOB INDIGIS3D_EXE "${INDIGIS3D_DIR_UNIV}/bin/win32/*.exe")

INSTALL(
    FILES       ${SQLITE_BINARIES} ${SPATIALITE_BIN} 
                ${PROJ_BIN} ${ICONV_BIN} ${GEOS_BIN} ${XERCESC_BIN} ${OSG_LIB} 
                ${OSGCONV} ${OSGVIEWER} ${OSG_PLUGINS} ${GDAL_EXE} ${GDAL_LIB}
                ${OSGEARTH_LIB} ${OSGEARTH_LIB}
                ${CURL_DEBUG_LIBS} ${CURL_DEBUG_EXE} ${CURL_RELEASE_LIBS} 
                ${CURL_RELEASE_EXE} ${EXPAT_BIN}
                ${PROJ_BIN} ${TIFF_BIN} ${BOOST_BIN} 
                ${JPEG_BIN} ${PNG_BIN} ${ZLIB_BIN} 
                ${FFMPEG_DLLS} ${FFMPEG_EXE} ${QWT_BIN} ${QT_BIN}
                ${INDIGIS3D_LIBS} ${INDIGIS3D_EARTH} ${INDIGIS3D_PLUGINS} ${INDIGIS3D_EXE}
               
    DESTINATION ${INSTALL_BINDIR}
)

# Copy data directory
INSTALL(
    DIRECTORY   $ENV{GDAL_DATA}
    DESTINATION ${INSTALL_GDALDATA}    
    PATTERN "CVS" EXCLUDE
)
# Copy config directory
INSTALL(
    DIRECTORY   ${INDIGIS3D_DIR_UNIV}/config
    DESTINATION ${CMAKE_INSTALL_PREFIX}
    PATTERN "CVS" EXCLUDE
)
# Copy tests directory
INSTALL(
    DIRECTORY   ${INDIGIS3D_DIR_UNIV}/tests
    DESTINATION ${CMAKE_INSTALL_PREFIX}
    PATTERN "CVS" EXCLUDE
)

# Copy data directory
INSTALL(
    DIRECTORY   ${INDIGIS3D_DIR_UNIV}/data
    DESTINATION ${CMAKE_INSTALL_PREFIX}
    PATTERN "CVS" EXCLUDE
    PATTERN ".#" EXCLUDE
    PATTERN "VectorData" EXCLUDE
    PATTERN "resource/images" EXCLUDE
    PATTERN ".html" EXCLUDE
    PATTERN ".qrc" EXCLUDE
)
